### ISSUE TITLE
Deflated JSON string map from Valetudo parsing fails due to SyntaxError

### ISSUE THREAD

**Issue by tlpbu** [Poeschl/Hassio-Addons#172]
**Which addon?**
ICantBelieveItsNotValetudo (Home Assistant Supervisor Addon)

**Describe the bug**
Deflated JSON string map from Valetudo (optionally base64 encoded) parsing fails with exception
```SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:86:42)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12)
    at work (/app/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
```

**To Reproduce**
1. Use Valetudo version 2021.01.1 on vacuum
2. Configure MQTT settings in Valetudo to provide map data
3. Configure addon settings to point to respective map data MQTT topic

**Expected behavior**
Successfully parse deflated JSON map data.
Implementation example potentially could be taken from https://github.com/alexkn/node-red-contrib-valetudo project.

**System**

* Supervisor version: supervisor-2021.01.7
* Host system version: Home Assistant OS 5.10

**Comment by Poeschl** [comment]
To fix the new map format ICantBeliveItsNotValetudo needs to get the suggested changes. The issue for that is https://github.com/Hypfer/ICantBelieveItsNotValetudo/issues/45.
Since the addon is only wrapping it, I will close the issue. (And might try to implement an fix there today)
