### ISSUE TITLE
some mistakes

### ISSUE THREAD

**Issue by Tao173** [Poeschl/Hassio-Addons#186]
MPD 
When using the previous version, it is normal and there is no problem, but the latest version will report an error
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ha_cloud_music/source_mpd.py:148
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 下午12:40:39 (1 occurrences)
Last logged: 下午12:40:39

[140339645999184] [55@0] {seekcur} Not playing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 648, in async_select_sound_mode
    await self.hass.async_add_executor_job(self.select_sound_mode, sound_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_cloud_music/media_player.py", line 616, in select_sound_mode
    self._media_player.reloadURL(media_url, media_position)
  File "/config/custom_components/ha_cloud_music/source_mpd.py", line 115, in reloadURL
    self.seek(position)
  File "/config/custom_components/ha_cloud_music/source_mpd.py", line 148, in seek
    self._client.seekcur(position)
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 381, in mpd_command
    return wrapper(self, name, args, callback)
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 473, in _execute
    return retval()
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 368, in command_callback
    res = function(self, self._read_lines())
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 311, in _parse_nothing
    for line in lines:
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 538, in _read_lines
    line = self._read_line()
  File "/usr/local/lib/python3.8/site-packages/mpd/base.py", line 527, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [55@0] {seekcur} Not playing

**System**
Core
Version
core-2021.2.3
supervisor-2021.02.9
Newest Version
supervisor-2021.02.9
Channel
stable
IP Address
192.168.4.226/24
Operating System
UnionTech OS Desktop 20 Home
Docker version
20.10.3

**Comment by Poeschl** [comment]
Could you please use the provided issue template for a bug report.

Thank you.
