### ISSUE TITLE
Error in log and map doesn't update

### ISSUE THREAD

**Issue by BertilJ** [Poeschl/Hassio-Addons#202]
**Which addon?**
ICantBelieveItsNotValetudo

**Describe the bug**
Errors in log and no map produced

**To Reproduce**

1. Start addon
2. See error in log:
```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:145:43)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12)
    at work (/app/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
```

**System**

* Supervisor version: supervisor-2021.03.4
* Host system version: Home Assistant OS 5.12

**Comment by Poeschl** [comment]
Please take a look at #187, maybe the issue could be solved with the information there.

**Comment by BertilJ** [comment]
This is my mistake, I forgot that I tried ValetudoRE instead and apparently the map data goes differently. I will test valetudo mapper instead. Appologies.

**Comment by Poeschl** [comment]
All good 😉
