### ISSUE TITLE
mopidy does not start

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [Poeschl/Hassio-Addons#312]
**Which addon?**

mopidy

**Describe the bug**

mopidy addon does not start displays the following errors in log:

```
AssertionError
[11:56:22] INFO: Start Mopidy....
** (process:626): WARNING **: 11:56:24.043: Failed to load shared library 'libgstreamer-1.0.so.0' referenced by the typelib: Error relocating /usr/lib/libgstreamer-1.0.so.0: g_pattern_spec_match_string: symbol not found
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 33, in <module>
    sys.exit(load_entry_point('Mopidy==3.1.1', 'console_scripts', 'mopidy')())
  File "/usr/bin/mopidy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/mopidy/__main__.py", line 7, in <module>
    from mopidy import commands
  File "/usr/lib/python3.9/site-packages/mopidy/commands.py", line 15, in <module>
    from mopidy.audio import Audio
  File "/usr/lib/python3.9/site-packages/mopidy/audio/__init__.py", line 2, in <module>
    from .actor import Audio
  File "/usr/lib/python3.9/site-packages/mopidy/audio/actor.py", line 8, in <module>
    from mopidy.audio import tags as tags_lib
  File "/usr/lib/python3.9/site-packages/mopidy/audio/tags.py", line 7, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/usr/lib/python3.9/site-packages/mopidy/internal/gi.py", line 8, in <module>
    from gi.repository import GLib, GObject, Gst
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gst.py", line 64, in <module>
    Element = override(Element)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
[11:56:24] INFO: Start Mopidy....
```

**To Reproduce**

1. install add-on
2. start add-on

**Expected behavior**

addon starting normally without crash
with 2.0.1 it seems to work. error is since 2.1.0

**Screenshots**

**System**

* Supervisor version: 
supervisor-2022.03.5
* Host system version: 
Home Assistant OS 7.6
RPI4

**Comment by priest1111** [comment]
I have the same problem, thanks

**Comment by Poeschl** [comment]
Will look into it after work.

Please don't comment with an "Me too" comment, please use the 👍 emote on the issue description to show that you are affected by the bug. 😉 Thx

**Comment by tofuSCHNITZEL** [comment]
Thanks!

**Comment by priest1111** [comment]
thanks and sorry for the bad post :+1:
