### ISSUE TITLE
Error when trying to play on MPD from media browser

### ISSUE THREAD

**Issue by akarpych** [Poeschl/Hassio-Addons#334]
**Which addon?**
Mopidy

**Describe the bug**
When trying to play audio from the media browser, an error appears

**To Reproduce**

1. Go to 'media browser'
2. Click on 'Text to Speech-Google-Play'

```Logger: homeassistant.components.websocket_api.http.connection
Source: components/mpd/media_player.py:474
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:53:46 (1 occurrences)
Last logged: 13:53:46

[139941019247872] [50@0] {add} directory or file not found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/mpd/media_player.py", line 474, in async_play_media
    await self._client.add(media_id)
  File "/usr/local/lib/python3.10/site-packages/mpd/asyncio.py", line 309, in __run
    await result._feed_from(self)
  File "/usr/local/lib/python3.10/site-packages/mpd/asyncio.py", line 45, in _feed_from
    line = await mpdclient._read_line()
  File "/usr/local/lib/python3.10/site-packages/mpd/asyncio.py", line 395, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [50@0] {add} directory or file not found
```

**Screenshots**

**System**

* Supervisor version: 2022.08.3
* Host system version: 2022.8.5

**Comment by akarpych** [comment]
No. The same error appears. I tried it on a completely new installation - the problem is the same.

**Comment by akarpych** [comment]
![2022-08-17_21-05-17](https://user-images.githubusercontent.com/73226493/185174830-3cfcd9da-67b4-4062-bf16-c1e46cdcf288.png)

**Comment by Poeschl** [comment]
I can reproduce the issue, but right no clue how to solve it :/

Will look at it again.

**Comment by akarpych** [comment]
How to install a previous version?

**Comment by Poeschl** [comment]
https://community.home-assistant.io/t/how-to-downgrade-addons/331223

**Comment by akarpych** [comment]
Unfortunately, I didn't have any backups.

**Comment by cheehuei** [comment]
Hi, just want to report that I am facing the same issue. I am not able to call media player service to play a local mp3 file nor a tts. Seems like the issue happens after upgrading to HA Core 2022.8.5. Downgrading to 2022.8.3, issue persists.
Thank you for looking into it.

**Comment by oftrash** [comment]
yeah same issue here

**Comment by shinyshoes16** [comment]
I have this issue as well.  Is there anything I can do to help troubleshoot or test a fix?  This has a big impact on my Home Assistant implementation

**Comment by oftrash** [comment]
@shinyshoes16 my work around was to completely remove Poeschi repo and i found a recent fork of it on version 2.1.1 

aka https://github.com/2468171796/Hassio-Addons-mpd and installed this version of Mopidy

**Comment by Llntrvr** [comment]
@shinyshoes16 / @cheehuei / @akarpych  my work around was to completely remove Poeschi repo and i found a recent fork of it on version 2.1.1

aka https://github.com/2468171796/Hassio-Addons-mpd and installed this version of Mopidy and it works again for me

**Comment by Llntrvr** [comment]
or you can just take my 2.1.1 version of just Mopidy 

https://github.com/Llntrvr/Hassio-Addons

**Comment by akarpych** [comment]
> https://github.com/Llntrvr/Hassio-Addons

Thanks!

**Comment by Poeschl** [comment]
Unfortunately, I'm not able to develop a fix this or next week. 

@Llntrvr so the version 2.1.1 still works?

**Comment by Llntrvr** [comment]
@Poeschl yeah sadly the newest version just does not want to play sound

**Comment by cheehuei** [comment]
Thank you, @Llntrvr . Version 2.1.1 works for me.

**Comment by akarpych** [comment]
I found a problem: if MPD and led FX use the same hdmi output at the same time, then this error appears. I put the default audio interface everywhere, and everything seemed to work.

**Comment by Olegz73** [comment]
Have the same problem mpd 2.2.0 , ha 2022.8.7

**Comment by Poeschl** [comment]
Short update:

Looked into it for a bit, it seems mopidy has issues to load the audio files via the link HA provides. It is available via the 
commandline inside of the addon, but mopidy trips somewhere.

**Comment by Poeschl** [comment]
It's still not fixed for mpd and mopidy

**Comment by whakru** [comment]
Точно такая же проблема.

**Comment by Olegz73** [comment]
Still not fix at now
