### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by thundergreen** [Poeschl/Hassio-Addons#68]
**Which addon?**

Valetudo-Mapper
**Describe the bug**

Starting the Addon throws an error shown below
**To Reproduce**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:05:15] INFO: Setup config
[21:05:15] INFO: Start valetudo-mapper

> valetudo-mapper@0.5.0 start /app
> node app.js

Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at Buffer.readUInt32BE (internal/buffer.js:295:5)
    at Jimp.getPixelColor (/app/node_modules/@jimp/core/dist/index.js:883:34)
    at Jimp.autocrop (/app/node_modules/@jimp/plugin-crop/dist/index.js:138:32)
    at /app/lib/Tools.js:244:31 {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
```

**Expected behavior**

**Screenshots**

**System**

* Supervisor version:  
* Host system version:

**Comment by thundergreen** [comment]
re-installing removed the error.. I let it open till next week if error comes back

**Comment by SebLz** [comment]
Same issue here. Not sure if it is linked, but I recently updated my vacuum firware to 
https://vacuumz.info/download/gen1/vacuum_4007_valetudo_re_0_9_3.pkg
Reinstalling the addon did not help here.

os: Ubuntu 18.04.4 LTS (on arm 64)
valetudo mapper: 1.3.0
supervisor: 219
HA: 0.108.9

**Comment by axilleas** [comment]
Reinstalling fixed it for me too.

**Comment by Poeschl** [comment]
I will close this, since re-installing fixes it.
